app:
  backendPort: 8000
  frontendPort: 8001
  key: "/etc/letsencrypt/live/points884.com/privkey.pem"
  fullchain: "/etc/letsencrypt/live/points884.com/fullchain.pem"
  localKey: "cert/server.key"
  localFullChain: "cert/server.cert"
  mulitiPlayerTimeout: 2000
